/*
 * $Id$
 * 
 * Copyright 2012 Exozet Games GmbH
 */
/**
 * 
 */
package com.payone.sdkdemoapp.gui;

import android.content.Intent;
import android.content.SharedPreferences.Editor;
import android.os.Bundle;
import android.view.View;
import android.widget.EditText;

import com.payone.sdkdemoapp.R;
import com.payone.sdkdemoapp.gui.base.InputActivity;
import com.payone.sdkdemoapp.model.PayoneRequestData;
import com.payone.sdkdemoapp.util.AppUtils;

/**
 * @author hendrik.apel
 * @version $Rev$ $Date$
 *
 */
public class PaymentDetailsDebitActivity extends InputActivity
{
    @Override
    public void onCreate(Bundle savedInstanceState)
    {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.layout_paymentdetails_debit);

        addHideKeyboardListener((EditText) findViewById(R.id.editTextPaymentAmount));
    }

    /**
     * button listener
     * @param view - generated by the system
     */
    public void onPreAuthorization(View view)
    {
        createRequest(true);
    }

    /**
     * button listener
     * @param view - generated by the system
     */
    public void onAuthorization(View view)
    {
        createRequest(false);
    }

    private void createRequest(boolean isPreAuthorization)
    {
        // gather data given in activity
        String paymentAmount = readInput(R.id.editTextPaymentAmount);
        String bankAccount = readInput(R.id.editTextPaymentBankAccount);
        String bankCode = readInput(R.id.editTextPaymentBankCode);

        // verify data
        if (!AppUtils.isStringValue(paymentAmount) || !AppUtils.isStringValue(bankAccount)
                || !AppUtils.isStringValue(bankCode))
        {
            // show message
            MessageViewActivity.showMessage(getString(R.string.keyPaymentInputError), this);
        }
        else if (!AppUtils.checkCredentials(this))
        {
            // show message
            MessageViewActivity.showMessage(getString(R.string.keyPaymentSettingsError), this);
        }
        else
        {
            // create PayoneRequestData object, store in RequestActivity and start RequestActivity
            PayoneRequestData request = PayoneRequestData.createDebitRequest(bankAccount, bankCode, paymentAmount,
                    isPreAuthorization);
            AppUtils.setRequestData(this, request);
            PaymentRequestActivity.REQUEST_DATA = request;
            Intent intent = new Intent(this, PaymentRequestActivity.class);
            startActivity(intent);
        }
    }

    /**
     * Store the given input in special preferences.
     */
    @Override
    protected void saveInput()
    {
        Editor editor = mData.edit();
        editor.putString(getString(R.string.idPreferencesInputAmount), readInput(R.id.editTextPaymentAmount));
        editor.putString(getString(R.string.idPreferencesInputBankAccount), readInput(R.id.editTextPaymentBankAccount));
        editor.putString(getString(R.string.idPreferencesInputBankCode), readInput(R.id.editTextPaymentBankCode));
        editor.commit();
    }

    /**
     * Restore the previous input from special preferences.
     */
    @Override
    protected void restoreInput()
    {
        setInput(R.id.editTextPaymentAmount, mData.getString(getString(R.string.idPreferencesInputAmount), ""));
        setInput(R.id.editTextPaymentBankAccount,
                mData.getString(getString(R.string.idPreferencesInputBankAccount), ""));
        setInput(R.id.editTextPaymentBankCode, mData.getString(getString(R.string.idPreferencesInputBankCode), ""));
    }

    /**
     * Reset all input fields.
     */
    @Override
    public void clearInputFields()
    {
        ((EditText) findViewById(R.id.editTextPaymentAmount)).setText("");
        ((EditText) findViewById(R.id.editTextPaymentBankAccount)).setText("");
        ((EditText) findViewById(R.id.editTextPaymentBankCode)).setText("");
    }
}
